### ISSUE TITLE
Markmon on windows fails

### ISSUE THREAD

**Issue by steveoh** [yyjhao/sublime-text-markmon#3]
I `npm install -g markmon` and then installed the pandoc utility. Then installed markmon via package install. When I run markmon command sublime text spits out this error:

> Markmon Server failed to initialize. Confirm executable path is correct in Markmon Setting. Command used:
> ['markmon', '--port', '3002', '--command', 'pandoc -t HTML5 --mathjax']
> Traceback (most recent call last):
>   File "./subprocess.py", line 1112, in _execute_child
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 524, in run_
>     return self.run(**args)
>   File "commands in C:\Users\agrc-arcgis\AppData\Roaming\Sublime Text 3\Installed Packages\Markmon real-time markdown preview.sublime-package", line 21, in run
>   File "markmon in C:\Users\agrc-arcgis\AppData\Roaming\Sublime Text 3\Installed Packages\Markmon real-time markdown preview.sublime-package", line 50, in set_running
>   File "markmon in C:\Users\agrc-arcgis\AppData\Roaming\Sublime Text 3\Installed Packages\Markmon real-time markdown preview.sublime-package", line 130, in setup_server
>   File "./subprocess.py", line 824, in **init**
>   File "./subprocess.py", line 1118, in _execute_child
> FileNotFoundError: [WinError 2] The system cannot find the file specified

I can successfully run markmon from the console so I believe the path is set correctly
![image](https://cloud.githubusercontent.com/assets/325813/4922170/cd653aa6-650f-11e4-831a-483800ecbf1b.png)

Is something in the code not passing the sublime text file correctly?

**Comment by nitech** [comment]
My experience matches @steveoh. When I tried to create the `sublime-text-markmon.sublime-settings` file, it turned out that there was no folder in `C:\Users\me\AppData\Roaming\Sublime Text 3\Packages\sublime-text-markmon`

I created the folder and edited the `CTRL+P` Preferences: Markmon Settings User, in where I added the following JSON. Hope this is of help to someone: 

``` js
{
    //On Windows try "markmon.cmd" if you get errors.
    //If markmon is not on your path you'll need to use a full path to it
    "executable": "C:\\Users\\me\\AppData\\Roaming\\npm\\markmon.cmd",
    "port": 3010,
    "pandoc_path": "C:\\Program Files (x86)\\Pandoc\\pandoc.exe",
    "command": "pandoc -t HTML5 --mathjax",
    "stylesheet": "D:\\somepath\\github-markdown.css",
    "projectdir": null
}
```

Replace "me" with your username. 

Also note that I added my own Github flavored css stylesheet. I found it at https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css
I replaced `.markdown-body` with `body`, and I had to add a bit of Markmon specific css to make the highlighter display nicely:

``` css
/* Markmon specific */
.last-change-marker {
  box-shadow: 1px 0 0 1px rgba(255, 69, 0, 0.5); 
}
.highlighter {
  position: absolute;
  border-bottom: 2px solid orangered;
  top: -10px;
  left: 0;
  width: 100%;
  box-shadow: 0 1px 1px white; 
}
```
